# Generated by Django 4.2.23 on 2026-08-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('hour', models.IntegerField()),
                ('price_tier', models.IntegerField()),
                ('solar_tier', models.IntegerField()),
                ('battery_tier', models.IntegerField()),
                ('action', models.CharField(max_length=32)),
                ('action_label', models.CharField(max_length=128)),
                ('q_value', models.FloatField()),
                ('alternatives', models.JSONField(default=list)),
                ('explanation', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
